### PR TITLE
Ensure gss log perms, redact passwords in gss logs and fix existing lint

### PR DESCRIPTION
**Pull request by ryan-beisner**

### CODE REVIEW

**Comment by ryan-beisner** [comment]
I just exercised a charm upgrade, then a remove-application and re-deploy, and both results produce the intended log file permissions:

```
-rw-r-----  1 root   root    201 Apr 12 19:21 glance-simplestreams-sync.log
```

**Comment by ryan-beisner** [comment]
Added tests, and a test run, confirms:
```
2018-04-12 19:29:09,293 __init__ INFO: OpenStackAmuletDeployment:  init
2018-04-12 19:29:09,293 _add_services INFO: OpenStackAmuletDeployment:  adding services
2018-04-12 19:29:09,293 _determine_branch_locations INFO: OpenStackAmuletDeployment:  determine branch locations
2018-04-12 19:29:18,985 _configure_services INFO: OpenStackAmuletDeployment:  configure services
2018-04-12 19:29:19 Starting deployment of beisner-serverstack:admin/beisner
2018-04-12 19:29:20 Deploying applications...
2018-04-12 19:29:27 Adding relations...
2018-04-12 19:29:27 Deployment complete in 7.72 seconds
2018-04-12 19:29:38,266 __init__ INFO: Waiting on extended status checks...
2018-04-12 19:29:38,268 _auto_wait_for_status INFO: Waiting for extended status on units for 5400s...
2018-04-12 19:29:38,268 _auto_wait_for_status DEBUG: Default extended status wait match:  contains READY (case-insensitive)
2018-04-12 19:29:38,269 _auto_wait_for_status DEBUG: Excluding services from extended status match: ['glance-simplestreams-sync']
2018-04-12 19:29:38,270 _auto_wait_for_status DEBUG: Waiting up to 5400s for extended status on services: ['rabbitmq-server', 'glance', 'keystone', 'percona-cluster']
2018-04-12 19:29:40,289 _auto_wait_for_status INFO: OK
2018-04-12 19:29:40,737 _initialize_tests DEBUG: openstack release val: 11
2018-04-12 19:29:40,739 _initialize_tests DEBUG: openstack release str: queens
2018-04-12 19:29:40,740 get_default_keystone_session DEBUG: Authenticating keystone admin...
2018-04-12 19:29:41,375 authenticate_glance_admin DEBUG: Authenticating glance admin...
2018-04-12 19:29:42,637 test_001_wait_for_image_sync DEBUG: Images: [u'auto-sync/ubuntu-trusty-14.04-amd64-server-20180404-disk1.img']
2018-04-12 19:29:45,038 run_cmd_unit DEBUG: glance-simplestreams-sync/1 `stat -c %a /etc/glance-simplestreams-sync/identity.yaml` command returned 0 (OK)
2018-04-12 19:29:45,040 test_050_gss_permissions_regression_check_lp1611987 DEBUG: Permissions on /etc/glance-simplestreams-sync/identity.yaml: 640
2018-04-12 19:29:46,572 run_cmd_unit DEBUG: glance-simplestreams-sync/1 `stat -c %a /etc/glance-simplestreams-sync/mirrors.yaml` command returned 0 (OK)
2018-04-12 19:29:46,573 test_050_gss_permissions_regression_check_lp1611987 DEBUG: Permissions on /etc/glance-simplestreams-sync/mirrors.yaml: 640
2018-04-12 19:29:47,905 run_cmd_unit DEBUG: glance-simplestreams-sync/1 `stat -c %a /var/log/glance-simplestreams-sync.log` command returned 0 (OK)
2018-04-12 19:29:47,905 test_050_gss_permissions_regression_check_lp1611987 DEBUG: Permissions on /var/log/glance-simplestreams-sync.log: 640
2018-04-12 19:29:47,905 test_102_service_catalog DEBUG: Checking keystone service catalog...
2018-04-12 19:29:47,909 convert_svc_catalog_endpoint_data_to_v3 WARNING: Endpoint ID and Region ID validation is limited to not null checks after v2 to v3 conversion
2018-04-12 19:29:47,917 validate_v3_svc_catalog_endpoint_data DEBUG: Validating v3 service catalog endpoint data...
2018-04-12 19:29:47,917 validate_v3_svc_catalog_endpoint_data DEBUG: actual: {u'image': [{u'url': u'http://10.5.0.11:9292', u'interface': u'internal', u'region': u'RegionOne', u'region_id': u'RegionOne', u'id': u'123c463b97bc47caadf33835469ed159'}, {u'url': u'http://10.5.0.11:9292', u'interface': u'admin', u'region': u'RegionOne', u'region_id': u'RegionOne', u'id': u'b3693b83852c4e919f8126c857df189f'}, {u'url': u'http://10.5.0.11:9292', u'interface': u'public', u'region': u'RegionOne', u'region_id': u'RegionOne', u'id': u'd7a22f79bc7b4f0ba393076edef7e82b'}], u'product-streams': [{u'url': u'http://10.5.0.13', u'interface': u'public', u'region': u'RegionOne', u'region_id': u'RegionOne', u'id': u'3b8e28c8029c4fb58f9504a091523b37'}, {u'url': u'http://10.5.0.13', u'interface': u'admin', u'region': u'RegionOne', u'region_id': u'RegionOne', u'id': u'6a5b70fc4aa04826a8a58c0fcbd9b6bf'}, {u'url': u'http://10.5.0.13', u'interface': u'internal', u'region': u'RegionOne', u'region_id': u'RegionOne', u'id': u'c189f98e5aab4022973ea1b135aee696'}], u'identity': [{u'url': u'http://10.5.0.14:5000/v3', u'interface': u'internal', u'region': u'RegionOne', u'region_id': u'RegionOne', u'id': u'5e545276e0f945a6a1a34eb89b5b521d'}, {u'url': u'http://10.5.0.14:35357/v3', u'interface': u'admin', u'region': u'RegionOne', u'region_id': u'RegionOne', u'id': u'afb89379c2b4466eaf93551960b0b561'}, {u'url': u'http://10.5.0.14:5000/v3', u'interface': u'public', u'region': u'RegionOne', u'region_id': u'RegionOne', u'id': u'c091be83c8a844b282566f46fa3fcb47'}]}
2018-04-12 19:29:47,921 validate_v3_svc_catalog_endpoint_data DEBUG: checking interface admin
2018-04-12 19:29:47,925 _validate_dict_data DEBUG: actual: {u'url': u'http://10.5.0.13', u'interface': u'admin', u'region': u'RegionOne', u'region_id': u'RegionOne', u'id': u'6a5b70fc4aa04826a8a58c0fcbd9b6bf'}
2018-04-12 19:29:47,927 _validate_dict_data DEBUG: expected: {'url': <bound method OpenStackAmuletUtils.valid_url of <charmhelpers.contrib.openstack.amulet.utils.OpenStackAmuletUtils object at 0x7f1c1efee9d0>>, 'interface': 'admin', 'region': 'RegionOne', 'region_id': <bound method OpenStackAmuletUtils.not_null of <charmhelpers.contrib.openstack.amulet.utils.OpenStackAmuletUtils object at 0x7f1c1efee9d0>>, 'id': <bound method OpenStackAmuletUtils.not_null of <charmhelpers.contrib.openstack.amulet.utils.OpenStackAmuletUtils object at 0x7f1c1efee9d0>>}
2018-04-12 19:29:47,929 validate_v3_svc_catalog_endpoint_data DEBUG: checking interface internal
2018-04-12 19:29:47,931 _validate_dict_data DEBUG: actual: {u'url': u'http://10.5.0.13', u'interface': u'internal', u'region': u'RegionOne', u'region_id': u'RegionOne', u'id': u'c189f98e5aab4022973ea1b135aee696'}
2018-04-12 19:29:47,932 _validate_dict_data DEBUG: expected: {'url': <bound method OpenStackAmuletUtils.valid_url of <charmhelpers.contrib.openstack.amulet.utils.OpenStackAmuletUtils object at 0x7f1c1efee9d0>>, 'interface': 'internal', 'region': 'RegionOne', 'region_id': <bound method OpenStackAmuletUtils.not_null of <charmhelpers.contrib.openstack.amulet.utils.OpenStackAmuletUtils object at 0x7f1c1efee9d0>>, 'id': <bound method OpenStackAmuletUtils.not_null of <charmhelpers.contrib.openstack.amulet.utils.OpenStackAmuletUtils object at 0x7f1c1efee9d0>>}
2018-04-12 19:29:47,933 validate_v3_svc_catalog_endpoint_data DEBUG: checking interface public
2018-04-12 19:29:47,933 _validate_dict_data DEBUG: actual: {u'url': u'http://10.5.0.13', u'interface': u'public', u'region': u'RegionOne', u'region_id': u'RegionOne', u'id': u'3b8e28c8029c4fb58f9504a091523b37'}
2018-04-12 19:29:47,937 _validate_dict_data DEBUG: expected: {'url': <bound method OpenStackAmuletUtils.valid_url of <charmhelpers.contrib.openstack.amulet.utils.OpenStackAmuletUtils object at 0x7f1c1efee9d0>>, 'interface': 'public', 'region': 'RegionOne', 'region_id': <bound method OpenStackAmuletUtils.not_null of <charmhelpers.contrib.openstack.amulet.utils.OpenStackAmuletUtils object at 0x7f1c1efee9d0>>, 'id': <bound method OpenStackAmuletUtils.not_null of <charmhelpers.contrib.openstack.amulet.utils.OpenStackAmuletUtils object at 0x7f1c1efee9d0>>}
2018-04-12 19:29:47,941 validate_v3_svc_catalog_endpoint_data DEBUG: checking interface admin
2018-04-12 19:29:47,942 _validate_dict_data DEBUG: actual: {u'url': u'http://10.5.0.11:9292', u'interface': u'admin', u'region': u'RegionOne', u'region_id': u'RegionOne', u'id': u'b3693b83852c4e919f8126c857df189f'}
2018-04-12 19:29:47,943 _validate_dict_data DEBUG: expected: {'url': <bound method OpenStackAmuletUtils.valid_url of <charmhelpers.contrib.openstack.amulet.utils.OpenStackAmuletUtils object at 0x7f1c1efee9d0>>, 'interface': 'admin', 'region': 'RegionOne', 'region_id': <bound method OpenStackAmuletUtils.not_null of <charmhelpers.contrib.openstack.amulet.utils.OpenStackAmuletUtils object at 0x7f1c1efee9d0>>, 'id': <bound method OpenStackAmuletUtils.not_null of <charmhelpers.contrib.openstack.amulet.utils.OpenStackAmuletUtils object at 0x7f1c1efee9d0>>}
2018-04-12 19:29:47,945 validate_v3_svc_catalog_endpoint_data DEBUG: checking interface internal
2018-04-12 19:29:47,945 _validate_dict_data DEBUG: actual: {u'url': u'http://10.5.0.11:9292', u'interface': u'internal', u'region': u'RegionOne', u'region_id': u'RegionOne', u'id': u'123c463b97bc47caadf33835469ed159'}
2018-04-12 19:29:47,946 _validate_dict_data DEBUG: expected: {'url': <bound method OpenStackAmuletUtils.valid_url of <charmhelpers.contrib.openstack.amulet.utils.OpenStackAmuletUtils object at 0x7f1c1efee9d0>>, 'interface': 'internal', 'region': 'RegionOne', 'region_id': <bound method OpenStackAmuletUtils.not_null of <charmhelpers.contrib.openstack.amulet.utils.OpenStackAmuletUtils object at 0x7f1c1efee9d0>>, 'id': <bound method OpenStackAmuletUtils.not_null of <charmhelpers.contrib.openstack.amulet.utils.OpenStackAmuletUtils object at 0x7f1c1efee9d0>>}
2018-04-12 19:29:47,949 validate_v3_svc_catalog_endpoint_data DEBUG: checking interface public
2018-04-12 19:29:47,951 _validate_dict_data DEBUG: actual: {u'url': u'http://10.5.0.11:9292', u'interface': u'public', u'region': u'RegionOne', u'region_id': u'RegionOne', u'id': u'd7a22f79bc7b4f0ba393076edef7e82b'}
2018-04-12 19:29:47,952 _validate_dict_data DEBUG: expected: {'url': <bound method OpenStackAmuletUtils.valid_url of <charmhelpers.contrib.openstack.amulet.utils.OpenStackAmuletUtils object at 0x7f1c1efee9d0>>, 'interface': 'public', 'region': 'RegionOne', 'region_id': <bound method OpenStackAmuletUtils.not_null of <charmhelpers.contrib.openstack.amulet.utils.OpenStackAmuletUtils object at 0x7f1c1efee9d0>>, 'id': <bound method OpenStackAmuletUtils.not_null of <charmhelpers.contrib.openstack.amulet.utils.OpenStackAmuletUtils object at 0x7f1c1efee9d0>>}
2018-04-12 19:29:47,952 validate_v3_svc_catalog_endpoint_data DEBUG: checking interface admin
2018-04-12 19:29:47,952 _validate_dict_data DEBUG: actual: {u'url': u'http://10.5.0.14:35357/v3', u'interface': u'admin', u'region': u'RegionOne', u'region_id': u'RegionOne', u'id': u'afb89379c2b4466eaf93551960b0b561'}
2018-04-12 19:29:47,954 _validate_dict_data DEBUG: expected: {'url': <bound method OpenStackAmuletUtils.valid_url of <charmhelpers.contrib.openstack.amulet.utils.OpenStackAmuletUtils object at 0x7f1c1efee9d0>>, 'interface': 'admin', 'region': 'RegionOne', 'region_id': <bound method OpenStackAmuletUtils.not_null of <charmhelpers.contrib.openstack.amulet.utils.OpenStackAmuletUtils object at 0x7f1c1efee9d0>>, 'id': <bound method OpenStackAmuletUtils.not_null of <charmhelpers.contrib.openstack.amulet.utils.OpenStackAmuletUtils object at 0x7f1c1efee9d0>>}
2018-04-12 19:29:47,954 validate_v3_svc_catalog_endpoint_data DEBUG: checking interface internal
2018-04-12 19:29:47,955 _validate_dict_data DEBUG: actual: {u'url': u'http://10.5.0.14:5000/v3', u'interface': u'internal', u'region': u'RegionOne', u'region_id': u'RegionOne', u'id': u'5e545276e0f945a6a1a34eb89b5b521d'}
2018-04-12 19:29:47,955 _validate_dict_data DEBUG: expected: {'url': <bound method OpenStackAmuletUtils.valid_url of <charmhelpers.contrib.openstack.amulet.utils.OpenStackAmuletUtils object at 0x7f1c1efee9d0>>, 'interface': 'internal', 'region': 'RegionOne', 'region_id': <bound method OpenStackAmuletUtils.not_null of <charmhelpers.contrib.openstack.amulet.utils.OpenStackAmuletUtils object at 0x7f1c1efee9d0>>, 'id': <bound method OpenStackAmuletUtils.not_null of <charmhelpers.contrib.openstack.amulet.utils.OpenStackAmuletUtils object at 0x7f1c1efee9d0>>}
2018-04-12 19:29:47,956 validate_v3_svc_catalog_endpoint_data DEBUG: checking interface public
2018-04-12 19:29:47,956 _validate_dict_data DEBUG: actual: {u'url': u'http://10.5.0.14:5000/v3', u'interface': u'public', u'region': u'RegionOne', u'region_id': u'RegionOne', u'id': u'c091be83c8a844b282566f46fa3fcb47'}
2018-04-12 19:29:47,956 _validate_dict_data DEBUG: expected: {'url': <bound method OpenStackAmuletUtils.valid_url of <charmhelpers.contrib.openstack.amulet.utils.OpenStackAmuletUtils object at 0x7f1c1efee9d0>>, 'interface': 'public', 'region': 'RegionOne', 'region_id': <bound method OpenStackAmuletUtils.not_null of <charmhelpers.contrib.openstack.amulet.utils.OpenStackAmuletUtils object at 0x7f1c1efee9d0>>, 'id': <bound method OpenStackAmuletUtils.not_null of <charmhelpers.contrib.openstack.amulet.utils.OpenStackAmuletUtils object at 0x7f1c1efee9d0>>}
2018-04-12 19:29:47,957 validate_memcache DEBUG: Checking memcached is running
2018-04-12 19:29:47,960 validate_services_by_name DEBUG: Checking status of system services...
2018-04-12 19:29:49,384 get_ubuntu_release_from_sentry DEBUG: glance/0 lsb_release: xenial
2018-04-12 19:29:50,737 validate_services_by_name DEBUG: glance/0 `sudo service memcached status` returned 0
2018-04-12 19:29:50,737 validate_memcache DEBUG: OK
2018-04-12 19:29:50,737 validate_memcache DEBUG: Checking memcache url is configured in /etc/glance/glance-api.conf
2018-04-12 19:29:50,739 validate_config_data DEBUG: Validating config file data (keystone_authtoken in /etc/glance/glance-api.conf on glance/0)...
2018-04-12 19:29:52,179 validate_memcache DEBUG: OK
2018-04-12 19:29:52,185 validate_memcache DEBUG: Checking memcache configuration in /etc/memcached.conf
2018-04-12 19:29:55,216 run_cmd_unit DEBUG: glance/0 `lsb_release -cs` command returned 0 (OK)
2018-04-12 19:29:55,217 validate_memcache DEBUG: Checking -l is set to ::1
2018-04-12 19:29:55,217 validate_memcache DEBUG: ::1
2018-04-12 19:29:55,217 validate_memcache DEBUG: Checking -p is set to 11211
2018-04-12 19:29:55,217 validate_memcache DEBUG: 11211
2018-04-12 19:29:55,217 validate_memcache DEBUG: OK
2018-04-12 19:29:55,217 validate_memcache DEBUG: Checking memcached is running
2018-04-12 19:29:55,217 validate_services_by_name DEBUG: Checking status of system services...
2018-04-12 19:29:56,603 get_ubuntu_release_from_sentry DEBUG: glance/0 lsb_release: xenial
2018-04-12 19:29:57,973 validate_services_by_name DEBUG: glance/0 `sudo service memcached status` returned 0
2018-04-12 19:29:57,975 validate_memcache DEBUG: OK
2018-04-12 19:29:57,976 validate_memcache DEBUG: Checking memcache url is configured in /etc/glance/glance-registry.conf
2018-04-12 19:29:57,976 validate_config_data DEBUG: Validating config file data (keystone_authtoken in /etc/glance/glance-registry.conf on glance/0)...
2018-04-12 19:29:59,429 validate_memcache DEBUG: OK
2018-04-12 19:29:59,433 validate_memcache DEBUG: Checking memcache configuration in /etc/memcached.conf
2018-04-12 19:30:02,149 run_cmd_unit DEBUG: glance/0 `lsb_release -cs` command returned 0 (OK)
2018-04-12 19:30:02,150 validate_memcache DEBUG: Checking -l is set to ::1
2018-04-12 19:30:02,150 validate_memcache DEBUG: ::1
2018-04-12 19:30:02,150 validate_memcache DEBUG: Checking -p is set to 11211
2018-04-12 19:30:02,150 validate_memcache DEBUG: 11211
2018-04-12 19:30:02,151 validate_memcache DEBUG: OK
```

**Comment by ryan-beisner** [comment]
Example of the problem log file, with a charm upgrade happening, then passwords logging as "redacted".

FWIW, the real passwords herein are insignificant and no longer in existence.

```
{'rabbit_userid': 'glance-simplestreams-sync', 'unit_name': 'glance-simplestreams-sync/1', 'admin_user': None, 'admin_tenant_id': None, 'auth_port': None, 'rabbit_password': 'sdYxxgGJhbFRbB4qb2p4SpJwcrjhsgxRbHRJ
ZMWx2HjSGpXTbjtNrhyk52Pjbpwk', 'auth_protocol': None, 'auth_host': None, 'service_protocol': None, 'rabbit_host': '10.5.0.9', 'service_port': None, 'rabbit_virtual_host': 'openstack', 'admin_tenant_name': None,
'service_host': None, 'api_version': None, 'admin_password': None}
{'rabbit_userid': 'glance-simplestreams-sync', 'unit_name': 'glance-simplestreams-sync/1', 'admin_user': None, 'admin_tenant_id': None, 'auth_port': None, 'rabbit_password': 'sdYxxgGJhbFRbB4qb2p4SpJwcrjhsgxRbHRJ
ZMWx2HjSGpXTbjtNrhyk52Pjbpwk', 'auth_protocol': None, 'auth_host': None, 'service_protocol': None, 'rabbit_host': '10.5.0.9', 'service_port': None, 'rabbit_virtual_host': 'openstack', 'admin_tenant_name': None,
'service_host': None, 'api_version': None, 'admin_password': None}
{'rabbit_userid': 'glance-simplestreams-sync', 'unit_name': 'glance-simplestreams-sync/1', 'admin_user': None, 'admin_tenant_id': None, 'auth_port': None, 'rabbit_password': 'sdYxxgGJhbFRbB4qb2p4SpJwcrjhsgxRbHRJ
ZMWx2HjSGpXTbjtNrhyk52Pjbpwk', 'auth_protocol': None, 'auth_host': None, 'service_protocol': None, 'rabbit_host': '10.5.0.9', 'service_port': None, 'rabbit_virtual_host': 'openstack', 'admin_tenant_name': None,
'service_host': None, 'api_version': None, 'admin_password': None}
{'rabbit_userid': 'glance-simplestreams-sync', 'unit_name': 'glance-simplestreams-sync/1', 'admin_user': None, 'admin_tenant_id': None, 'auth_port': None, 'rabbit_password': 'sdYxxgGJhbFRbB4qb2p4SpJwcrjhsgxRbHRJ
ZMWx2HjSGpXTbjtNrhyk52Pjbpwk', 'auth_protocol': None, 'auth_host': None, 'service_protocol': None, 'rabbit_host': '10.5.0.9', 'service_port': None, 'rabbit_virtual_host': 'openstack', 'admin_tenant_name': None,
'service_host': None, 'api_version': None, 'admin_password': None}
{'rabbit_userid': 'glance-simplestreams-sync', 'unit_name': 'glance-simplestreams-sync/1', 'admin_user': None, 'admin_tenant_id': None, 'auth_port': None, 'rabbit_password': 'sdYxxgGJhbFRbB4qb2p4SpJwcrjhsgxRbHRJ
ZMWx2HjSGpXTbjtNrhyk52Pjbpwk', 'auth_protocol': None, 'auth_host': None, 'service_protocol': None, 'rabbit_host': '10.5.0.9', 'service_port': None, 'rabbit_virtual_host': 'openstack', 'admin_tenant_name': None,
'service_host': None, 'api_version': None, 'admin_password': None}
{'rabbit_userid': 'glance-simplestreams-sync', 'unit_name': 'glance-simplestreams-sync/1', 'admin_user': None, 'admin_password': '<redacted>', 'rabbit_host': '10.5.0.9', 'admin_tenant_id': None, 'service_port':
None, 'rabbit_virtual_host': 'openstack', 'admin_tenant_name': None, 'auth_port': None, 'rabbit_password': '<redacted>', 'auth_protocol': None, 'api_version': None, 'auth_host': None, 'service_host': None, 'serv
ice_protocol': None}
```

**Comment by ryan-beisner** [comment]
The bug driving this, for reference:  https://bugs.launchpad.net/charm-glance-simplestreams-sync/+bug/1762429

**Review by thedac — APPROVED** [review]
Looks good. Merging.

**Pull request merged**
